; PHP settings for development

[PHP]
post_max_size       = 20M
upload_max_filesize = 20M
max_execution_time  = 120
memory_limit        = 256M
display_errors      = On
error_reporting     = E_ALL

[Date]
date.timezone = America/Sao_Paulo
